import { mount, flushPromises } from '@vue/test-utils';
import axios from 'axios';
import AdminDashboard from '@/views/admin/AdminDashboard.vue';
import AdminAnnouncements from '@/views/admin/AdminAnnouncements.vue';
import AdminPostEditor from '@/views/admin/AdminPostEditor.vue';
import AdminAnnouncementEditor from '@/views/admin/AdminAnnouncementEditor.vue';
vi.mock('axios');
beforeEach(() => { axios.get.mockReset(); axios.post.mockReset(); axios.patch.mockReset(); axios.delete.mockReset(); });
const options = (params = {}) => ({ global: { stubs: { RouterLink: { props: ['to'], template: '<a><slot /></a>' } }, mocks: { $route: { params, query: {} }, $router: { push: vi.fn() }, $store: { state: { Login: { token: 'admin' } } } } } });
it('현황은 서버 집계를 표시하고 실패 뒤 재시도한다', async () => {
  axios.get.mockRejectedValueOnce(new Error()).mockResolvedValueOnce({ data: { announcements: 3, bootcamps: 2, questions: 7, answers: 9, members: 4 } });
  const wrapper = mount(AdminDashboard, options());
  await flushPromises();
  await wrapper.get('[data-test="retry"]').trigger('click');
  await flushPromises();
  expect(wrapper.get('[data-test="stat-questions"]').text()).toContain('7');
});
it('공고 삭제는 확인 뒤에만 요청하고 취소하면 원본 목록을 유지한다', async () => {
  axios.get.mockResolvedValue({ data: { content: [{ id: 7, title: '삭제 공고', language: ['JAVA'], company: 'DEMP' }], last: true, number: 0 } });
  axios.delete.mockResolvedValue({ data: { cleanupPending: false } });
  const wrapper = mount(AdminAnnouncements, options());
  await flushPromises();
  await wrapper.get('[data-test="delete-7"]').trigger('click');
  expect(axios.delete).not.toHaveBeenCalled();
  await wrapper.get('[data-test="cancel-delete"]').trigger('click');
  expect(wrapper.text()).toContain('삭제 공고');
  await wrapper.get('[data-test="delete-7"]').trigger('click');
  await wrapper.get('[data-test="confirm-delete"]').trigger('click');
  await flushPromises();
  expect(axios.delete).toHaveBeenCalledWith('/api/admin/announcements/7');
});
it('기존 HTML 질문을 Markdown으로 불러와 안전한 HTML로 저장하며 중복 제출을 막는다', async () => {
  axios.get.mockResolvedValue({ data: { id: 7, questionId: 7, title: '원본', content: '<h2>기존 제목</h2><p><u>밑줄</u></p>', username: 'author', hashtags: ['JAVA'] } });
  let finish;
  axios.patch.mockImplementation(() => new Promise(resolve => { finish = resolve; }));
  const wrapper = mount(AdminPostEditor, { ...options({ id: '7' }), props: { kind: 'questions' } });
  await flushPromises();
  expect(wrapper.get('#admin-content').element.value).toContain('## 기존 제목');
  expect(wrapper.get('.admin-original h2').text()).toBe('기존 제목');
  await wrapper.get('#admin-content').setValue('## 수정 제목\n\n<u>밑줄</u>');
  await wrapper.get('form').trigger('submit');
  await wrapper.get('form').trigger('submit');
  expect(axios.patch).toHaveBeenCalledTimes(1);
  expect(axios.patch.mock.calls[0]).toEqual(['/api/admin/questions/7', expect.objectContaining({ content: expect.stringContaining('<h2>수정 제목</h2>') })]);
  expect(axios.patch.mock.calls[0][1].content).toContain('<u>밑줄</u>');
  finish({ data: {} }); await flushPromises();
});
it('공고 수정은 기존 HTML과 필드를 복원하고 파일을 선택하지 않으면 image를 보내지 않는다', async () => {
  axios.get.mockResolvedValue({ data: { title: '원본 공고', company: { name: 'DEMP' }, content: '<h2>기존</h2>', language: ['JAVA', 'SPRING'], announcementType: 'EDU', position: 'BACKEND', minCareer: 0, maxCareer: 0, payment: 0, startedDate: '2026-01-01T00:00:00', deadLineDate: '2026-12-31T00:00:00', accessUrl: 'https://example.test', image: '' } });
  axios.patch.mockResolvedValue({ data: { cleanupPending: false } });
  const wrapper = mount(AdminAnnouncementEditor, options({ id: '7' }));
  await flushPromises();
  expect(wrapper.get('#admin-content').text()).toContain('기존');
  await wrapper.setData({ form: { ...wrapper.vm.form, content: '<h2>수정</h2>' } });
  await wrapper.get('form').trigger('submit');
  await flushPromises();
  const [url, data] = axios.patch.mock.calls[0];
  expect(url).toBe('/api/admin/announcements/7');
  expect(data.has('image')).toBe(false);
  expect(data.getAll('language')).toEqual(['JAVA', 'SPRING']);
  expect(data.get('content')).toContain('<h2>수정</h2>');
});
it('관리자 저장의 400 오류는 입력값 안내를 표시하고 작성 내용을 보존한다', async () => {
  axios.get.mockResolvedValue({ data: { id: 7, questionId: 7, title: '원본', content: '<p>기존 본문</p>', username: 'author', hashtags: [] } });
  axios.patch.mockRejectedValue({ response: { status: 400 } });
  const wrapper = mount(AdminPostEditor, { ...options({ id: '7' }), props: { kind: 'questions' } });
  await flushPromises();
  await wrapper.get('#admin-content').setValue('수정한 본문');
  await wrapper.get('form').trigger('submit'); await flushPromises();
  expect(wrapper.get('[role="alert"]').text()).toContain('입력값');
  expect(wrapper.get('#admin-content').element.value).toBe('수정한 본문');
});
